version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: myhost
    environment:
      POSTGRES_DB: flixxo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"